version: "3.5"

services:
  umi-dev_build:
    image: weschen/umi-dev:20200304.4
    container_name: "umi-dev_build"
    environment: 
      REACT_APP_HOST_IP_ADDRESS: "这是从docker-compose中传入的文件"
    volumes:
      - /root/data/dist/:/usr/src/app/dist
    command: 
      ["npm","run","build"]

  umi-dev_web:
    image: nginx
    ports:
      - 8002:80
    container_name: "umi-dev_web"
    restart: unless-stopped
    volumes:
      - /root/data/dist/:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
